# Generated by Django 4.2.7 on 2023-11-25 19:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic_creator.imageelement')),
                ('text_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic_creator.textelement')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_url', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('write_url', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('panels', models.ManyToManyField(related_name='comic_panels', to='comic_creator.panel')),
            ],
        ),
    ]
